//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilkServer.SubServer {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class SubServerSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SubServerSettings defaultInstance = ((SubServerSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SubServerSettings())));
        
        public static SubServerSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string MasterIPAddress {
            get {
                return ((string)(this["MasterIPAddress"]));
            }
            set {
                this["MasterIPAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4520")]
        public int OutgoingMasterServerPeerPort {
            get {
                return ((int)(this["OutgoingMasterServerPeerPort"]));
            }
            set {
                this["OutgoingMasterServerPeerPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int ConnectRetryInterval {
            get {
                return ((int)(this["ConnectRetryInterval"]));
            }
            set {
                this["ConnectRetryInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string PublicIPAddress {
            get {
                return ((string)(this["PublicIPAddress"]));
            }
            set {
                this["PublicIPAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4531")]
        public int SubServerTcpPort {
            get {
                return ((int)(this["SubServerTcpPort"]));
            }
            set {
                this["SubServerTcpPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5056")]
        public int SubServerUdpPort {
            get {
                return ((int)(this["SubServerUdpPort"]));
            }
            set {
                this["SubServerUdpPort"] = value;
            }
        }
    }
}
